# Generated by Django 5.2 on 2025-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_faces/'),
        ),
    ]
