# Generated by Django 5.2 on 2025-04-19 12:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_image_cropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
