# Generated by Django 5.2 on 2025-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_visitor_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
