# Generated by Django 5.2 on 2025-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='addressing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
