# Generated by Django 5.2 on 2025-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_log_addressing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='addressing',
        ),
        migrations.AddField(
            model_name='visitor',
            name='addressing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
